FROM docker.elastic.co/elasticsearch/elasticsearch:7.10.0

RUN bin/elasticsearch-plugin install --batch https://github.com/o19s/elasticsearch-learning-to-rank/releases/download/v1.5.4-es7.10.0/ltr-plugin-v1.5.4-es7.10.0.zip
