version: "3.3"
services:
  flink:
    build: ./flink-twitter/
    env_file:
      - twitter.env
    environment:
      - REDIS_HOST=redis
    depends_on:
      - "redis"
  classifier:
    build: ./zero-shot-classifier/
    ports:
      - "8080:8080"
    environment:
      - NLI_MODEL=facebook/bart-large-mnli
      #- NLI_MODEL=/home/jeff/berlin-buzzwords-2021/nli/models/MNLI/
  elasticsearch:
    build: ./elasticsearch/
    ports:
      - "9200:9200"
    networks:
      - elastic
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    networks:
      - elastic
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
networks:
  elastic:
    driver: bridge
