version: "3.3"
services:
  flink:
    build: ./flink-twitter/
    env_file:
      - twitter.env
    environment:
      - REDIS_HOST=redis
    depends_on:
      - "redis"
  classifier:
    build: ./zero-shot-classifier/
    ports:
      - "8080:8080"
  elasticsearch:
    build: ./elasticsearch/
    ports:
      - "9200:9200"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
