version: "3.3"
services:
  flink:
    build: ./flink-twitter/
    #image: "jzemerick/bbuzz-flink-twitter:1.0"
    env_file:
      - twitter.env
    environment:
      - REDIS_HOST=redis
    depends_on:
      - "redis"
  classifier:
    build: ./zero-shot-classifier/
    #image: "jzemerick/bbuzz-zero-shot:1.0"
    ports:
      - "8080:8080"
#  elasticsearch:
#    build: ./elasticsearch-ltr/
    #image: "jzemerick/elasticsearch-ltr:7.8.0"
#    ports:
#      - "9200:9200"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
