apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: mlops
  namespace: bbuzz
spec:
  version: 7.12.1
  nodeSets:
  - name: default
    count: 3
    config:
      node.store.allow_mmap: false
    podTemplate:
      spec:
        initContainers:
        - name: install-plugins
          command:
          - sh
          - -c
          - |
            bin/elasticsearch-plugin install -b https://github.com/o19s/elasticsearch-learning-to-rank/releases/download/v1.5.4-es7.12.1/ltr-plugin-v1.5.4-es7.12.1.zip
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: mlops
  namespace: bbuzz
spec:
  version: 7.12.1
  count: 1
  elasticsearchRef:
    name: mlops
    