apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: mlops
  namespace: bbuzz
spec:
  version: 7.12.1
  nodeSets:
  - name: default
    count: 3
    config:
      node.store.allow_mmap: false
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: mlops
  namespace: bbuzz
spec:
  version: 7.12.1
  count: 1
  elasticsearchRef:
    name: mlops